server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:hotelscheduler;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: INFO
    org.springframework.security: INFO

app:
  security:
    jwt:
      secret: "YXZlcnlTdHJvbmdAMTIzNDU2Nzg5MDEyMzQ1Ni0tLXN1cGVyU2VjcmV0Ig=="

camel:
  servlet:
    mapping:
      context-path: /api/*